# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, improve-win-launcher ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-win-packrlauncher-job:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./gradlew --refresh-dependencies --no-build-cache -i --stacktrace clean :PackrLauncher:build
        env:
          PACKR_GITHUB_MAVEN_USERNAME: ${{ github.actor }}
          PACKR_GITHUB_MAVEN_TOKEN: ${{ secrets.GITHUB_TOKEN }}